### PR TITLE
Using retrofit2 and recycler view

### PR DESCRIPTION
**Pull request by javiergamarra**
A PR changing the async task with retrofit (with GSON adapter and parsing). Retrofit with callback isn't perfect (but can be cancellable) and there is still an orientation problem (eventbus, retain instance or RxJava will be of help there).

And showing the results in a recycler view.

### CODE REVIEW

**Comment by mdelapenya** [comment]
Hey  @nhpatt, we are using model classes from https://github.com/craftsmanship-toledo/katangapp-api proyect. Could you use them to avoid duplicating classes?

Thanks!

**Comment by mdelapenya** [comment]
For the retrofit change, this blogpost will add clarity over it: https://androidtutorialmagic.wordpress.com/android-asynctask-and-its-dark-side/retrofit-networking-in-android-tutorial-replacement-of-asynctask-and-volley/

**Comment by javiergamarra** [comment]
Yes, I should write down my problems with Android Async Tasks somewhere (maybe writing a post) but there are several posts about the problems Async Tasks have, like this [link](http://blog.danlew.net/2014/06/21/the-hidden-pitfalls-of-asynctask/).

But my main gripes are:
1. They are not easily cancelable (cancel() does not work as you think)
2. If you embed them in an activity is really easy to have memory leaks, if you implement them in their own class you have to deal with the burden of passing the context (and memory leaks too)
3. They are **very** coupled with the activity! retrofit just needs a callback and you can pass it around layers. If you extract the async task to another class (and you should) you either have to pass the activity and couple all your code :S :S or create a new callback.
4. Orientation problems. Retrofit also has this problem but a little bit diminished, when you rotate the activity in an async task usually you have code in the post execute manipulating a now-defunt activity (crash!)
5. Very verbose API that does not help implementing background calls at all
6. You cannot concatenate, combine... several calls or you would get a huge mess.

Also you are using Apache HTTP that is deprecated in new versions (because other set of problems), the recommended http library is OkHttp (retrofit is already using it).

Retrofit helps with:
1. Either you use it synchronously or async but it is not aware of the activity by default
2. It's really easy to set up a REST call

But it doesn't help with the orientation problem. For that the next pull should integrate an event bus, a fragment with retain, RxJava or loaders (that were created specifically because the async tasks problems)...

We can talk about android architecture or this problems in depth by hangout or slack (I have a channel to answer doubs) :)

**Comment by javiergamarra** [comment]
This PR will work 'as is' if the 'Serializable PR' is merged, it's already updated to use the existing classes instead of GSON annotated ones. It will only need to update the version number, I think.

**Comment by nhpatt** [comment]
Updated API version :)

**Comment by javiergamarra** [comment]
and rebased :P

**Comment by mdelapenya** [comment]
Closing, sent here for review: https://github.com/nhpatt/katangapp-android/pull/1

**Pull request closed without merging**
